export const LAST_ERROR_LABEL = 'Last error';
export const DAILY_ERROR_COUNT_LABEL = 'Daily error count';
export const SINCE_LAST_SYNC_LABEL = 'Since last sync';
export const MINUTES_LABEL = 'min';
export const SECONDS_LABEL = 'sec';
export const ERRORS_LAST_HOUR_LABEL = 'Errors in last hour';
export const WARNINGS_LAST_HOUR_LABEL = 'Warnings in last hour';
export const OPERATIONS_LAST_HOUR_LABEL = 'Operations in last hour';
export const AVERAGE_RESPONSE_TIME_LABEL = 'Average response time';